---
title: "Analyse questionnaire TF/PTF"
format: 
  html:
    embed-resources: true
---

```{r, echo=F, warning=F, message=F}
library(tidyverse) |> suppressPackageStartupMessages()
```

This quarto report shows how the data from the questionnaire can be extracted and printed. Further analysis of the literature findings can proceed from here onwards. The data are stored in a googlesheets and you can use the `googlesheets4` package to extract them. Importing the data can be set up with a user-defined wrapper function.

```{r, message=F}
library(googlesheets4) |> suppressPackageStartupMessages()

# currently no authorization is required
# this will be changed once we are collecting real data
gs4_deauth()

source(here::here("source/R/import-data-questionnaire.R"))

url_sheet <- paste0("https://docs.google.com/spreadsheets/d/",
                    "13Qcj2Eg_oI9aUy7vL_34XdF-oucMppBdhk2w70AQMHk/",
                    "edit?gid=1214981089#gid=1214981089")

data <- import_data_questionaire(url_sheet)
```

<br>

We print some selected columns:

```{r, echo = F}
data %>%
  select(unique_id, email, english, code_public, 
         tf_or_ptf, soildescriptor, ref_method, wrb_soiltype,
         url_pdf) %>%
  DT::datatable(rownames = F)
```

